"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const WinId = {
    LoginWindow: "id_LoginWindow",
    MainWindow: "mainWindow",
    RTCWindow: "id_RtcWindow",
    TabBarItemMenuWindow: "id_TabBarItemMenuWindow",
    DownloadCenter: "id_DownloadCenter",
    meetWindowUUID: "meetWindow",
    screenToolsWindowUUID: "screenTools",
    choseScreenWindowUUID: "choseScreen",
    openVideoBoxWindowUUID: "openVideoBox",
    openPIPVideoBoxWindowUUID: "openPIPVideoBox",
    videoPreviewUUID: "videoPreview",
    imagePreviewUUID: "imagePreview",
    classImagePreviewUUID: "classImagePreviewUUID",
    settingInMeetUUID: "settingInMeet",
    settingBeforeMeetUUID: "settingBeforeMeet",
    whiteBoardUUID: "white_board",
    annotationUUID: "annotation",
    setupFileDownloadUUID: "setupFileDownload",
    miniMeetingWinUUID: "miniMeetingWin",
    screenRecordUUID: "screenRecord",
    screenRecordControlUUID: "screenRecordControl",
    updateAppPromptWindow: "updateAppPromptWindow",
    screenshotWindow: "screenshotWindow",
    projectionBox: "projectionBox",
    DevHelperWindow: "id_DevHelperWindow",
    stuShowBox: "stuShowBox",
    NetStateView: "id_NetStateView",
    DataMigrationWindow: "id_DataMigrationWindow",
    PersonInfoWindow: "id_PersonInfoWindow",
    KeyConflictWindow: "id_KeyConflictWindow",
    TrayPopWindow: "id_TrayPopWindow",
    speechRecognitionUUID: "speech_recognition",
    translateSettingUUID: "translate_setting",
    accountOfflineWindow: "account_offline",
    cxRobotUUID: "cx_robot",
    KetangFloatingWindowUUID: "id_KetangFloatingWindow",
    CallWindow: "id_CallWindow",
    ProjectionPreToastUUID: "id_ProjectionPreToastUUID",
    DevToolsVerifyWindow: "id_DevToolsVerifyWindow",
};
module.exports = WinId;
exports.default = WinId;
//# sourceMappingURL=WinId.js.map